### ISSUE TITLE
IdService wastes IDs on read misses

### ISSUE THREAD

**Issue by drevell** [urbanairship/datacube#34]
When looking up an address contaning a field value that doesn't exist, IdService will allocate a unique ID for that field value. Reads should never allocate unique IDs.

So 

`IdService.getId(int dimensionNum, byte[] input, int numIdBytes)`

should change to something like 

`IdService.getId(int dimensionNum, byte[] input, int numIdBytes, boolean allocateIfAbsent)`

**Comment by AWinterman** [comment]
addressed in https://github.com/urbanairship/datacube/pull/61
